language: python
python:
- '3.5'
services:
- postgresql
install: pip install -r requirements-dev.txt
script: python setup.py test
deploy:
  provider: pypi
  user: sdementen
  password:
    secure: jPJOUnrIkRary3QQGcuz4TgyP3ChoCJpRnDZYJmdTKh4GPOGXtYAKi6vGqlrlnVlnAxzopXfzzvHkEBH9RYtH/l7ylIGMSFwW245wJPsj7yq+by4LbufRT8EMJqhS2UofU3feOgHrwKhgqXcH7SOEwKpRN/xpm0nc4Wh+HHpL4s=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: sdementen/gnucash-utilities
    all_branches: master
    condition: $PYTHON_VERSION=3.5
